spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olxdb
    username: root
    password: Temp1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect
